# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(2) do |config|

    config.vm.network "private_network", ip: "10.1.1.99"
    config.vm.network :forwarded_port, guest:4444, host:4444

    config.vm.provider "virtualbox" do |v|
        v.memory=5000
        v.cpus=4
        v.customize ["modifyvm", :id, "--vram", "128"]
    end

    #Configure red hat 6.5 box parameters
    config.vm.define "grid", primary: true do |grid|
        grid.vm.box = "ubuntu/trusty64"
    end
    config.vm.provision :shell, :path => "bootstrap.sh"
    config.vm.provision "shell", inline: "sudo service hub start"
    config.vm.provision "shell", inline: "sudo service node start"

end