version: '2'
services:
    selenium_hub:
        image: selenium/hub
        container_name: selenium_hub
        privileged: true
        ports:
            - 4444:4444
        environment:
            - GRID_TIMEOUT=120000
            - GRID_BROWSER_TIMEOUT=120000
        networks:
            - selenium_grid_internal

    chrome:
        image: selenium/node-chrome
        privileged: true
        depends_on:
            - selenium_hub
        environment:
            - no_proxy=localhost
            - TZ=Europe/London
            - HUB_PORT_4444_TCP_ADDR=selenium_hub
            - HUB_PORT_4444_TCP_PORT=4444
        networks:
            - selenium_grid_internal
        volumes:
            - /dev/shm:/dev/shm

    chrome_debug:
        image: selenium/node-chrome-debug
        privileged: true
        depends_on:
            - selenium_hub
        ports:
            - 52000:5900
        environment:
            - SCREEN_HEIGHT=1080
            - SCREEN_WIDTH=1920
            - no_proxy=localhost
            - TZ=Europe/London
            - HUB_PORT_4444_TCP_ADDR=selenium_hub
            - HUB_PORT_4444_TCP_PORT=4444
        networks:
            - selenium_grid_internal
        volumes:
            - /dev/shm:/dev/shm

networks:
    selenium_grid_internal: