# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  config.vm.box = "ubuntu/xenial64"

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false


  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network "private_network", ip: "10.1.1.99"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"
  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    vb.gui = false
  
    # Customize the amount of memory on the VM:
    vb.memory = "4096"
  end
 # config.vm.provision "docker" do |d|
 #    d.run "selenium/hub",
 #      args: "-p 4444:4444 --name selenium-hub"
 #    d.run "selenium/node-chrome-1",
 #      image: "selenium/node-chrome",
 #      args: "-v /dev/shm:/dev/shm --link selenium-hub:hub"
 #    d.run "selenium/node-chrome-2",
 #      image: "selenium/node-chrome",
 #      args: "-v /dev/shm:/dev/shm --link selenium-hub:hub"
 #    d.run "selenium/node-chrome-3",
 #      image: "selenium/node-chrome",
 #      args: "-v /dev/shm:/dev/shm --link selenium-hub:hub"
 #    d.run "selenium/node-chrome-4",
 #      image: "selenium/node-chrome",
 #      args: "-v /dev/shm:/dev/shm --link selenium-hub:hub"
 #    d.run "selenium/node-chrome-5",
 #      image: "selenium/node-chrome",
 #      args: "-v /dev/shm:/dev/shm --link selenium-hub:hub"
 #  end

   config.vm.provision "ansible" do |ansible|
        ansible.playbook = "playbook.yml"
        ansible.sudo = true
        # ansible.verbose = true
        ansible.verbose = "vvv"
        ansible.extra_vars = {
        ansible_python_interpreter: "/usr/bin/python3.5",
    }
    end

end
